# Generated by Django 4.2.7 on 2023-11-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="categories",
        ),
        migrations.DeleteModel(
            name="CourseCollectionBridge",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="course.category",
            ),
            preserve_default=False,
        ),
    ]
