# Generated by Django 4.2.7 on 2023-11-22 17:25

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="url",
        ),
        migrations.AddField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=course.utils.get_attachment_file
            ),
        ),
    ]
